on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - develop
      - master
    paths-ignore:
      - '*.md'


env:
  NODE_VERSION: lts/iron
  AWS_REGION: eu-central-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          path: cdk

      - name: zip authorization lambda and upload
        working-directory: cdk
        run: |
          cd lib/assets/lambdas/authorization
          npm install
          echo ${{github.run_number}} >> version.txt
          echo COGNITO_USER_POOL_ID=\$AUTHZ_COGNITO_USERPOOL_ID >> .env.template
          zip -r authorization.zip .
          aws s3 cp authorization.zip s3://apiable/public/_lambdas/authorization-${{github.run_number}}.zip
          aws s3 cp authorization.zip s3://apiable/public/_lambdas/authorization-latest.zip
          

